teams:
  - name: lf-staff
    maintainers:
      - ryjones
    members:
      - davidwboswell
      - minyu66
  - name: lfdt-brazil-chapter-editors
    maintainers:
      - ryjones
    members:
      - thelinuxfoundation
  - name: lfdt-european-chapter-editors
    maintainers:
      - ryjones
    members:
      -  mh-put-00
  - name: lfdt-india-chapter-editors
    maintainers:
      - ryjones
    members:
      - knagware9
  - name: lfdt-japan-chapter-editors
    maintainers:
      - ryjones
    members:
      - thelinuxfoundation
  - name: lfdt-latinoamerica-chapter-editors
    maintainers:
      - ryjones
    members:
      - thelinuxfoundation

repositories:
  - name: governance
    teams:
      lf-staff: maintain
    visibility: public
  - name: LFDT-Brazil-Chapter
    teams:
      lf-staff: maintain
      lfdt-brazil-chapter-editors: maintain
    visibility: public
  - name: LFDT-European-Chapter
    teams:
      lf-staff: maintain
      lfdt-european-chapter-editors: maintain
    visibility: public
  - name: LFDT-India-Chapter
    teams:
      lf-staff: maintain
      lfdt-india-chapter-editors: maintain
    visibility: public
  - name: LFDT-Japan-Chapter
    teams:
      lf-staff: maintain
      lfdt-japan-chapter-editors: maintain
    visibility: public
  - name: LFDT-Latinoamerica-Chapter
    teams:
      lf-staff: maintain
      lfdt-latinoamerica-chapter-editors: maintain
    visibility: public
