teams:
  - name: lf-staff
    maintainers:
      - ryjones
    members:
      - christinaharter
      - daniela-barbosa
      - davidwboswell
      - minyu66
  - name: lfdt-brazil-chapter-editors
    maintainers:
      - jteider
    members:
      - Jeankteixeira
      - JoaoDant4s
      - LuizGuFaMartins
      - marianabenedett
  - name: lfdt-european-chapter-editors
    maintainers:
      - mh-put-00
  - name: lfdt-india-chapter-editors
    maintainers:
      - knagware9
    members:
      - A1kartikey
      - BiniWorld
      - RedKnight13
      - ankita-p17
      - garimamiet
      - sharmawiki
  - name: lfdt-japan-chapter-editors
    maintainers:
      - satota2
    members:
      - dnakashima
      - sfuji822
  - name: lfdt-latinoamerica-chapter-editors
    maintainers:
      - ryjones
    members:
      - thelinuxfoundation

repositories:
  - name: governance
    teams:
      lf-staff: maintain
    visibility: public
  - name: LFDT-Brazil-Chapter
    teams:
      lf-staff: maintain
      lfdt-brazil-chapter-editors: maintain
    visibility: public
  - name: LFDT-European-Chapter
    teams:
      lf-staff: maintain
      lfdt-european-chapter-editors: maintain
    visibility: public
  - name: LFDT-India-Chapter
    teams:
      lf-staff: maintain
      lfdt-india-chapter-editors: maintain
    visibility: public
  - name: LFDT-Japan-Chapter
    teams:
      lf-staff: maintain
      lfdt-japan-chapter-editors: maintain
    visibility: public
  - name: LFDT-Latinoamerica-Chapter
    teams:
      lf-staff: maintain
      lfdt-latinoamerica-chapter-editors: maintain
    visibility: public
